"""Report generation: console table, markdown report, GTT CSV, optional email."""

from __future__ import annotations

import csv
import os
import smtplib
from datetime import datetime
from email.message import EmailMessage
from pathlib import Path

from .playbook import MarketState, Position, StockMetrics


def _fmt_inr(x: float) -> str:
    return f"₹{x:,.0f}"


def _fmt_pct(x: float, dp: int = 2) -> str:
    return f"{x:+.{dp}f}%" if x != 0 else "0.00%"


# ============================================================
# Console output
# ============================================================


def _stocks_skipped_for_sizing(selected: list[StockMetrics], positions: list[Position]) -> list[StockMetrics]:
    held_symbols = {p.symbol for p in positions}
    return [s for s in selected if s.symbol not in held_symbols]


def print_console(
    market: MarketState,
    ranked: list[StockMetrics],
    selected: list[StockMetrics],
    positions: list[Position],
    capital_inr: float,
    deployed_inr: float,
    cfg: dict,
):
    print()
    print("=" * 78)
    print(f"  SATURDAY RUNNER — {datetime.now().strftime('%Y-%m-%d %H:%M IST')}")
    print(f"  Capital: {_fmt_inr(capital_inr)}    Universe: NIFTY 50")
    print("=" * 78)

    print()
    print("STEP 1 — Market state")
    print(f"  NIFTY close:          {market.nifty_close:,.2f}")
    print(
        f"  NIFTY 40-WMA:         {market.nifty_40w_sma:,.2f}    "
        f"→ {'TREND-ON' if market.trend_on else 'TREND-OFF'}"
    )
    print(f"  India VIX:            {market.india_vix:.2f}")
    print(
        f"  Vol scaling:          ×{market.vol_scaling_factor:.2f}  "
        f"(effective target = {market.target_portfolio_vol_pct:.1f}%)"
    )
    for n in market.notes:
        print(f"  ! {n}")

    print()
    print("STEPS 2–4 — Quality-passing top-12 momentum candidates")
    print(
        f"  {'Rank':>4}  {'Symbol':<12}  {'Sector':<22}  {'Mom12-1':>8}  "
        f"{'Vol(ann)':>9}  {'ATR%':>6}  {'Q':>2}  PEAD"
    )
    for i, m in enumerate(ranked[:12], start=1):
        pead = m.pead_note or "-"
        print(
            f"  {i:>4}  {m.symbol:<12}  {m.sector:<22}  "
            f"{m.momentum_12_1*100:>7.1f}%  {m.realised_vol_4w_annual*100:>8.1f}%  "
            f"{m.atr_pct_14d:>5.2f}%  {m.quality_score:>2}  {pead}"
        )

    print()
    print(f"STEPS 5–7 — Final portfolio ({len(positions)} of {cfg['portfolio']['target_positions']} target)")
    if not positions:
        print("  ⚠  NO POSITIONS PASSED. Hold cash this week.")
    else:
        print(
            f"  {'Symbol':<12}  {'Sector':<22}  {'Sh':>4}  {'Entry':>9}  "
            f"{'Stop':>9}  {'Stop%':>6}  {'Notional':>10}  {'Wt%':>5}  {'Risk':>7}"
        )
        for p in positions:
            stop_pct = (p.last_close - p.final_stop_price) / p.last_close * 100.0
            print(
                f"  {p.symbol:<12}  {p.sector:<22}  {p.shares:>4}  "
                f"{p.last_close:>9,.2f}  {p.final_stop_price:>9,.2f}  "
                f"{stop_pct:>5.2f}%  {_fmt_inr(p.notional_inr):>10}  "
                f"{p.realised_weight_pct:>4.1f}%  {_fmt_inr(p.risk_inr):>7}"
            )
        total_risk = sum(p.risk_inr for p in positions)
        print(
            f"  {'TOTAL':<12}  {'':22}  {'':>4}  {'':>9}  {'':>9}  {'':>6}  "
            f"{_fmt_inr(deployed_inr):>10}  "
            f"{deployed_inr/capital_inr*100:>4.1f}%  {_fmt_inr(total_risk):>7}"
        )
        cash = capital_inr - deployed_inr
        print(
            f"  Cash buffer: {_fmt_inr(cash)} ({cash/capital_inr*100:.1f}%)   "
            f"Total at-risk: {total_risk/capital_inr*100:.2f}% of capital"
        )

    skipped = _stocks_skipped_for_sizing(selected, positions)
    if skipped:
        print()
        print("  Selected but skipped at sizing step:")
        for s in skipped:
            note = "; ".join(s.notes) if s.notes else "(unknown)"
            print(f"    {s.symbol:<12}  ₹{s.last_close:,.0f}   reason: {note}")

    print()
    print("=" * 78)


# ============================================================
# Markdown report
# ============================================================


def write_markdown(
    out_path: Path,
    market: MarketState,
    ranked: list[StockMetrics],
    selected: list[StockMetrics],
    positions: list[Position],
    capital_inr: float,
    deployed_inr: float,
    cfg: dict,
):
    lines: list[str] = []
    today = datetime.now().strftime("%Y-%m-%d %H:%M IST")
    lines.append(f"# Weekly portfolio — {today}")
    lines.append("")
    lines.append(
        "Generated by `automation/saturday-runner/run.py` per the playbook in "
        "`docs/research-runs/2026-05-02-systematic-swing-trading-evidence-based-playbook.md`."
    )
    lines.append("")
    lines.append(f"**Capital:** {_fmt_inr(capital_inr)}     **Universe:** NIFTY 50     "
                 f"**Holdings:** {len(positions)} / {cfg['portfolio']['target_positions']}")
    lines.append("")
    lines.append("## Step 1 — Market state")
    lines.append("")
    lines.append(f"- NIFTY close: **{market.nifty_close:,.2f}**")
    lines.append(f"- NIFTY 40-week SMA: **{market.nifty_40w_sma:,.2f}** → "
                 f"**{'TREND-ON' if market.trend_on else 'TREND-OFF'}**")
    lines.append(f"- India VIX: **{market.india_vix:.2f}**")
    lines.append(f"- Vol scaling: **×{market.vol_scaling_factor:.2f}** "
                 f"(effective target {market.target_portfolio_vol_pct:.1f}%)")
    for n in market.notes:
        lines.append(f"- ⚠ {n}")
    lines.append("")
    lines.append("## Steps 2–4 — Top-12 candidates (quality-passing, momentum-ranked, PEAD-overlaid)")
    lines.append("")
    lines.append("| # | Symbol | Sector | Mom 12-1 | Vol(ann) | ATR% | Quality | PEAD note |")
    lines.append("|---|---|---|---:|---:|---:|---:|---|")
    for i, m in enumerate(ranked[:12], start=1):
        lines.append(
            f"| {i} | `{m.symbol}` | {m.sector} | "
            f"{m.momentum_12_1*100:+.1f}% | {m.realised_vol_4w_annual*100:.1f}% | "
            f"{m.atr_pct_14d:.2f}% | {m.quality_score}/3 | {m.pead_note or '-'} |"
        )
    lines.append("")
    lines.append("## Steps 5–7 — Final portfolio")
    lines.append("")
    if not positions:
        lines.append("⚠ **NO POSITIONS PASSED ALL FILTERS.** Hold cash this week.")
    else:
        lines.append(
            "| Symbol | Sector | Shares | Entry | Stop | Stop% | Notional | Wt% | Risk | Exit by | Notes |"
        )
        lines.append(
            "|---|---|---:|---:|---:|---:|---:|---:|---:|---|---|"
        )
        for p in positions:
            stop_pct = (p.last_close - p.final_stop_price) / p.last_close * 100.0
            note_text = "; ".join(p.notes) if p.notes else "-"
            lines.append(
                f"| `{p.symbol}` | {p.sector} | {p.shares} | "
                f"₹{p.last_close:,.2f} | ₹{p.final_stop_price:,.2f} | {stop_pct:.2f}% | "
                f"{_fmt_inr(p.notional_inr)} | {p.realised_weight_pct:.1f}% | "
                f"{_fmt_inr(p.risk_inr)} | {p.target_exit_date} | {note_text} |"
            )
        total_risk = sum(p.risk_inr for p in positions)
        cash = capital_inr - deployed_inr
        lines.append("")
        lines.append(f"**Deployed:** {_fmt_inr(deployed_inr)} ({deployed_inr/capital_inr*100:.1f}%)     "
                     f"**Cash buffer:** {_fmt_inr(cash)} ({cash/capital_inr*100:.1f}%)     "
                     f"**Total at-risk:** {_fmt_inr(total_risk)} ({total_risk/capital_inr*100:.2f}%)")

    skipped = _stocks_skipped_for_sizing(selected, positions)
    if skipped:
        lines.append("")
        lines.append("### Selected but skipped at sizing step")
        lines.append("")
        lines.append("| Symbol | Last close | Reason |")
        lines.append("|---|---:|---|")
        for s in skipped:
            note = "; ".join(s.notes) if s.notes else "(unknown)"
            lines.append(f"| `{s.symbol}` | ₹{s.last_close:,.0f} | {note} |")

    lines.append("")
    lines.append("## Step 8 — Execution checklist")
    lines.append("")
    lines.append("- [ ] Compare to last week's holdings (kept what's still in top-12, exit what fell out)")
    lines.append("- [ ] Place buy orders Monday at 09:30 (limit at last close + 0.30%)")
    lines.append("- [ ] Upload `gtt_orders.csv` to your broker for stop-loss GTT orders")
    lines.append("- [ ] Set calendar reminders for `Exit by` dates (time stops)")
    lines.append("- [ ] Halve / exit any held name with earnings within 3 trading days")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Realistic monthly net return band per playbook §8.4: **+0.6% to +1.1%**.")
    lines.append("Worst-month drawdown expectation: **−4% to −8%**. "
                 "Expect a 4-loss streak ~5× per year at 60% win rate. **Do not deviate.**")
    out_path.write_text("\n".join(lines))


# ============================================================
# GTT CSV (for upload to Upstox / Zerodha web UI)
# ============================================================


def write_gtt_csv(out_path: Path, positions: list[Position]):
    """CSV format that you can review and either:
      (a) hand-enter into the broker's GTT UI, or
      (b) feed to a small uploader script using the broker's REST API.
    Columns are intentionally broker-agnostic; map them in your uploader.
    """
    fields = [
        "symbol",
        "isin",
        "side",
        "quantity",
        "trigger_price",
        "limit_price",
        "order_type",
        "validity",
        "tag",
    ]
    with out_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for p in positions:
            limit_price = round(p.final_stop_price * 0.997, 2)
            w.writerow(
                {
                    "symbol": p.symbol,
                    "isin": p.isin,
                    "side": "SELL",
                    "quantity": p.shares,
                    "trigger_price": round(p.final_stop_price, 2),
                    "limit_price": limit_price,
                    "order_type": "SL-L",
                    "validity": "GTT",
                    "tag": "saturday-runner-stop",
                }
            )


# ============================================================
# Email (optional)
# ============================================================


def send_email(subject: str, body: str, attachments: list[Path], cfg: dict) -> bool:
    if not cfg["output"]["email_enabled"]:
        return False
    host = os.environ.get("SMTP_HOST")
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER")
    pw = os.environ.get("SMTP_PASS")
    to = os.environ.get("EMAIL_TO")
    if not all([host, user, pw, to]):
        print("  email_enabled=true but env vars missing (SMTP_HOST/SMTP_USER/SMTP_PASS/EMAIL_TO). Skipping.")
        return False
    msg = EmailMessage()
    prefix = cfg["output"].get("email_subject_prefix", "")
    msg["Subject"] = f"{prefix} {subject}".strip()
    msg["From"] = user
    msg["To"] = to
    msg.set_content(body)
    for ap in attachments:
        if ap.exists():
            data = ap.read_bytes()
            msg.add_attachment(
                data,
                maintype="text",
                subtype="markdown" if ap.suffix == ".md" else "csv",
                filename=ap.name,
            )
    with smtplib.SMTP(host, port) as s:
        s.starttls()
        s.login(user, pw)
        s.send_message(msg)
    return True
